name: Build the API project
run-name: Building the API project
on:
  push:
    branches:
      - main
      - feature/github-action-pipeline
    paths:
      - hide_yourself/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./hide_yourself
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package verify
